### ISSUE TITLE
panic: runtime error: integer divide by zero

### ISSUE THREAD

**Issue by rudijs** [influxdata/influxdata-docker#28]
Hi,

Am seeing this error in both 0.13.0-alpine and 1.0.2-alpine docker official images.

I'm running the official images inside OpenShift Origin:

OpenShift Master:v1.3.0
Kubernetes Master:v1.3.0+52492b4

The VM running this is Centos7 w/ Selinux enforcing.

I enter into a running container and want to start the influx CLI:

```
/ $ influx
Visit https://enterprise.influxdata.com to register for updates, InfluxDB server management, and monitoring.
Connected to http://localhost:8086 version 1.0.2
InfluxDB shell version: 1.0.2
> panic: runtime error: integer divide by zero
[signal 0x8 code=0x1 addr=0x61ce00 pc=0x61ce00]

goroutine 1 [running]:
panic(0x783500, 0xc82000a050)
        /usr/local/go/src/runtime/panic.go:481 +0x3e6
github.com/peterh/liner.(*State).refreshMultiLine(0xc8200723c0, 0xc8200df3b8, 0x2, 0x2, 0xc82000b868, 0x1, 0x2, 0x1, 0x0, 0x0)
        /root/go/src/github.com/peterh/liner/line.go:159 +0xf0
github.com/peterh/liner.(*State).refresh(0xc8200723c0, 0xc8200df3b8, 0x2, 0x2, 0xc82000b868, 0x1, 0x2, 0x1, 0x0, 0x0)
        /root/go/src/github.com/peterh/liner/line.go:94 +0x8f
github.com/peterh/liner.(*State).PromptWithSuggestion(0xc8200723c0, 0x7f41d8, 0x2, 0x0, 0x0, 0x1, 0x0, 0x0, 0x0, 0x0)
        /root/go/src/github.com/peterh/liner/line.go:822 +0x1e64
github.com/peterh/liner.(*State).Prompt(0xc8200723c0, 0x7f41d8, 0x2, 0x0, 0x0, 0x0, 0x0)
        /root/go/src/github.com/peterh/liner/line.go:567 +0x6c
github.com/influxdata/influxdb/cmd/influx/cli.(*CommandLine).mainLoop(0xc820072280, 0x0, 0x0)
        /root/go/src/github.com/influxdata/influxdb/cmd/influx/cli/cli.go:195 +0x17e
github.com/influxdata/influxdb/cmd/influx/cli.(*CommandLine).Run(0xc820072280, 0x0, 0x0)
        /root/go/src/github.com/influxdata/influxdb/cmd/influx/cli/cli.go:181 +0x1483
main.main()
        /root/go/src/github.com/influxdata/influxdb/cmd/influx/main.go:112 +0x964
```

Not sure there's much else I can do other than report this issue, but if there is please let me know.

Thanks.

**Comment by rudijs** [comment]
Oh, my bad I think. The docs say:

```
At the moment, you cannot use docker exec to run the influx client since docker exec will not properly allocate a TTY. This is due to a current bug in Docker that is detailed in docker/docker#8755.
```

If this is correct, we can just close this issue for now?

Thanks again.

**Comment by jsternberg** [comment]
Yep. That seems to be it. I'll consider seeing if I can find a way to get the influx binary to just abort when it can't use a TTY like that. It might not be an issue in future versions since I think I added a feature to 1.1 where it will just read stdin. In the case where stdin isn't a TTY (when this bug happens), it will just very confusingly close...

Not sure that's better, but I'm not sure what else to do about that in a way that doesn't interfere with normal usage.
