### ISSUE TITLE
source panic:: failed to load tag values for _field

### ISSUE THREAD

**Issue by cellcubeBaMa** [influxdata/influxdata-docker#526]
The data explorer doesn't display _field value options and displays the error `failed to load tag values for _field` instead.

In the docker logs the following stacktrace is displayed:
 ```
ts=2021-09-13T07:21:30.789836Z lvl=info msg="Execute source panic" log_id=0WZWKFTW000 service=storage-reads error="panic: runtime error: invalid memory address or nil pointer dereference" stacktrace="goroutine 1548 [running]:
  runtime/debug.Stack(0xc000c54480, 0x3ce5500, 0x2169a8b)
	  /home/circleci/.tools/go/src/runtime/debug/stack.go:24 +0x9f
  github.com/influxdata/flux/execute.(*executionState).do.func1.1(0xc0011c2bd0)
	  /home/circleci/go/pkg/mod/github.com/influxdata/flux@v0.124.0/execute/executor.go:287 +0x20f
  panic(0x39202a0, 0x4bf35b0)
	  /home/circleci/.tools/go/src/runtime/panic.go:965 +0x1b9
  github.com/influxdata/influxdb/v2/v1/services/storage.(*Store).measurementFields.func1(0x0, 0x0)
	  /home/circleci/go/src/github.com/influxdata/influxdb/v1/services/storage/store.go:554 +0x24
  panic(0x393c260, 0xc00135db60)
	  /home/circleci/.tools/go/src/runtime/panic.go:965 +0x1b9
  github.com/influxdata/influxdb/v2/v1/services/storage.(*Store).measurementFields(0xc000b2d320, 0x3d2a038, 0xc001356c80, 0xc002c36ba8, 0x0, 0x0, 0x0, 0x0)
	  /home/circleci/go/src/github.com/influxdata/influxdb/v1/services/storage/store.go:557 +0x2ea
  github.com/influxdata/influxdb/v2/v1/services/storage.(*Store).TagValues(0xc000b2d320, 0x3d2a038, 0xc001356c80, 0xc00135db30, 0x0, 0xc002c36ca0, 0x416e3a, 0x20)
	  /home/circleci/go/src/github.com/influxdata/influxdb/v1/services/storage/store.go:414 +0x3ca
  github.com/influxdata/influxdb/v2/storage/flux.(*tagValuesIterator).Do(0xc001329480, 0xc00135aa60, 0x4a2828, 0x613efbfa)
	  /home/circleci/go/src/github.com/influxdata/influxdb/storage/flux/reader.go:955 +0x162
  github.com/influxdata/influxdb/v2/query/stdlib/influxdata/influxdb.(*Source).processTables(0xc003c7c9c0, 0x3d2a038, 0xc001356c80, 0x3d0cfc8, 0xc001329480, 0x16a450b21449edab, 0x16a450b213862247, 0x0)
	  /home/circleci/go/src/github.com/influxdata/influxdb/query/stdlib/influxdata/influxdb/source.go:76 +0x96
  github.com/influxdata/influxdb/v2/query/stdlib/influxdata/influxdb.(*readTagValuesSource).run(0xc003c7c9c0, 0x3d2a038, 0xc001356c80, 0x885d92bb2dda2e1c, 0x215315e)
	  /home/circleci/go/src/github.com/influxdata/influxdb/query/stdlib/influxdata/influxdb/source.go:492 +0x17f
  github.com/influxdata/influxdb/v2/query/stdlib/influxdata/influxdb.(*Source).Run(0xc003c7c9c0, 0x3d2a038, 0xc001356c80)
	  /home/circleci/go/src/github.com/influxdata/influxdb/query/stdlib/influxdata/influxdb/source.go:56 +0x34d
  github.com/influxdata/flux/execute.(*executionState).do.func1(0xc0011c2bd0, 0xc002dbaae0, 0x3d2bab0, 0xc003c7c9c0)
	  /home/circleci/go/pkg/mod/github.com/influxdata/flux@v0.124.0/execute/executor.go:292 +0x1f7
  created by github.com/influxdata/flux/execute.(*executionState).do
	  /home/circleci/go/pkg/mod/github.com/influxdata/flux@v0.124.0/execute/executor.go:262 +0xda
```

I have an Influx instance running inside docker (FROM influxdb:2.0.8), which is running on Ubuntu 20.04.3 LTS (GNU/Linux 5.4.0-80-generic x86_64), which afaik is running in a virtual machine. I am mapping `/var/lib/influxdb2` onto a local folder for persistence.

The data explorer worked without issue last friday, I have no idea what changed.

**Comment by cellcubeBaMa** [comment]
some additional things I noticed just now:
- I have existing dashboards -> they work and when I open an existing cell it displays the _field list without issue
- when I create a new dashboard the same error occurs when I add a cell and try to display the _field list (e.g. Filter > _field instead of Filter > _measurement)

**Comment by cellcubeBaMa** [comment]
aaaand it just started working again, out of the blue
I'll report back if it changes again

**Comment by cellcubeBaMa** [comment]
overall behavior is a bit weird
the error just occured again, but when I go into the `Script Editor` and write a query for some _field, the query works ... and when I switch back to the Query Builder GUI no error occurs when listing all _fields
